language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
- stable

script:
- npm test
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- ./tools/continuous-deployment.travis.sh
- node node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
- node node_modules/.bin/codecov
